# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d23bd4cdc7a0482d4357099dd755a3cd6f877c914ae5c9772bb538444b9ba34dcbac3971bad93c80d941428d813b794415b360f90824c1e91e77ea6810e77c

test:
  secret_key_base: a740158c5ae668e5880929353604712e760f697c602ac9c7914afa85eac3b5b54e1de19ac4ead8663acff7434d763b301529d49ff89c2f91a951c6d53df331b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
